server:
  port: 8080
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /

aladhan:
 api:
  base-url: https://api.aladhan.com/v1/timings
 delay: 1000

timezone:
 api:
  base-url: https://api.geotimezone.com/public
 delay: 1000

location:
  api:
    base-url: https://nominatim.openstreetmap.org
  delay: 1000